### ISSUE TITLE
New release on pypi

### ISSUE THREAD

**Issue by cburgmer** [cburgmer/upsidedown#6]
See #5

**Comment by jaraco** [comment]
I'd still like to see this.

**Comment by cburgmer** [comment]
Hey, sorry for not coming back earlier. I lost my pypi credentials and there's no quick and easy way to get this back. Happy for pointers though.

**Comment by jaraco** [comment]
Have you tried the [reset password](https://pypi.python.org/pypi?%3Aaction=forgotten_password_form) link? Maybe you no longer have the registered e-mail address. Also, if you have previously associated your account with an OpenID provider, you can log in with that to regain access. If neither of those work, the solution is to post a [support request](http://sourceforge.net/p/pypi/support-requests/).

After you regain access, if you would add me as an owner, I can serve as a backup admin for the project.

**Comment by cburgmer** [comment]
I created a support request: https://sourceforge.net/p/pypi/support-requests/510/ 
Thanks!

**Comment by xeBuz** [comment]
@cburgmer Any news with the release on `pypi`?

**Comment by cburgmer** [comment]
Thanks for pinging. I've just provided my new contact details, so we'll have to wait for progress there. I must have dropped the notification on the sourceforge tracker.

**Comment by OrangutanGaming** [comment]
Have you got a reply?

**Comment by cburgmer** [comment]
No reply since 2016-01-28

**Comment by jaraco** [comment]
The custody of PyPI has changed since your original request. You May have better luck with the [new process](https://pypi.org/help/#login-problem). Hope that helps.

**Comment by cburgmer** [comment]
My account has been restored on PyPi.

I've made all three of maintainers both here on Github and there on PyPi. Welcome on board.

I hope this works for all of you!

**Comment by jaraco** [comment]
Cool. Thanks @cburgmer. Based on that access, I created #7 to automate releases (using my PyPI credentials)... and tagged v0.4, which [failed here](https://travis-ci.org/cburgmer/upsidedown/jobs/450511875). Looks like Python 3.4 is required now.

**Comment by jaraco** [comment]
After bumping the Python version, the [deploy succeeded](https://travis-ci.org/cburgmer/upsidedown/jobs/450512658)!
